# Project-wide Gradle settings.

# AndroidX
android.useAndroidX=true

# Jetifier
android.enableJetifier=true

# Gradle JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Gradle performance
org.gradle.parallel=true
org.gradle.caching=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
